language: node_js
node_js:
- 8
jobs:
  include:
  - stage: test
    script: npm run eslint
deploy:
  provider: heroku
  api_key:
    secure: vkfhPV8XjTnaW7Ksp8JG5/gqco0Hap2xcYVKJ1rV9FTbC/93+P6wCRzKRNVao31neNckvojcNYs8hdxMNgOLtDMQrsiLEUEmpPbsvdK1W1xvW1CDBpWQESj4axNDDFTXgdVOwtcEocbSKcB0s2RkVpi5GoK7TG1RUjwxAdWdu81J41HFRn9i6sLwAJGgXgvgpW+AqGwKWomcukV25iSDLHR5Wntiq5rDfM8vzIwdLeTPzpC7M3Ihnw2+s5DuPnKqBVbQk+4igrBlzjgeXhbcBdlLoQ9RaFESds1BSaNhFx9CTXyMjMhZNqPBmWla48LMysCbadijKumXBRYpw3QHnXvIRGTDWafPiaHLCLwqrmPlIZw26HnoTN8xWn1uYdiqxE7pNaY36YiGlgB/KxKiosTsFPgH8PA9hkARqf1gSEWnJQ02TPuhIR5l8OLXcSt3hj8t8Wvc04mFDSbpf/d2iDGOKyNp98LbyvS8TDOmDkzYiFEkCNyx5t4BqX46n8E7/JQDI6OZvOvyJD4xtzT17mmk2cgmEk2Vj1SUoyRQPT7cCTNJAD4prJTLpRY6a6nRjzdGV95oGFazEjd96DcVg2MDUXafG6GYnd/2mlp3wc7IaGFHMOgqDxSrtXvlGR68VY+X/skMiQkjHmW2jXQLFB9mWwIVNcsiVW4agmCVQ2c=
  app: mind-map-app
  run:
  - npm install:server
  - npm build
  - npm start:prod
